version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt || true

  build:
    commands:
      - echo "Running build phase..."
      - echo "No actual build yet. Just testing pipeline."

artifacts:
  files:
    - '**/*'